apps/order/urls.py
from django.urls import path

from apps.order.views import (
    CartTemplateView, CartAddView, CartRemoveView, CartClearView,
    CheckoutTemplateView,
)

app_name = 'order'

urlpatterns = [
    path('cart/', CartTemplateView.as_view(), name='cart'),
    path('add/<pk>/', CartAddView.as_view(), name='cart-add'),
    path('remove/<pk>/', CartRemoveView.as_view(), name='cart-remove'),
    path('clear/', CartClearView.as_view(), name='cart-clear'),
    path('checkout/', CheckoutTemplateView.as_view(), name='checkout'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('', include('apps.order.urls', namespace='order')),
    path('api/v1/', include('apps.api.v1.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('users/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('soon/', TemplateView.as_view(
        template_name='soon.html',
        extra_context={'title': 'some title'}
    ), name='soon'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apps/order/models.py
from django.db import models
from django.contrib.auth import get_user_model

from apps.core.models import Product


class Order(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.TextField()
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return str(self.pk)


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

apps/order/forms.py
from django import forms

from apps.order.models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('complete',)

apps/order/views.py
from django.views.generic import View, TemplateView, RedirectView
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse

from apps.core.models import Product
from apps.order.cart import Cart
from apps.order.models import OrderProduct
from apps.order.forms import OrderForm


class CartTemplateView(TemplateView):
    template_name = 'order/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        print(len(context['cart']))
        return context


class CartAddView(View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        product = get_object_or_404(Product, pk=pk)
        cart = Cart(request)
        cart.add(product)
        return redirect('core:product-list')


class CartRemoveView(View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        product = get_object_or_404(Product, pk=pk)
        cart = Cart(request)
        cart.remove(product)
        return redirect('order:cart')


class CartClearView(RedirectView):
    pattern_name = 'core:index'

    def get_redirect_url(self, *args, **kwargs):
        Cart(self.request).clear()
        return super().get_redirect_url(*args, **kwargs)


class CheckoutTemplateView(TemplateView):
    template_name = 'order/checkout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        return context

    def post(self, request, *args, **kwargs):

        if request.user.is_authenticated:
            form_params = request.POST.copy()
            form_params.update({
                'user': request.user,
                'name': request.user.name,
                'surname': request.user.surname,
                'phone': request.user.phone,
                'email': request.user.email,
            })
            form = OrderForm(form_params)
        else:
            form = OrderForm(request.POST)

        if form.is_valid():
            order = form.save()
            cart = Cart(request)
            for item in cart:
                OrderProduct.objects.create(
                    order=order,
                    product=item['product'],
                    quantity=item['quantity']
                )
            cart.clear()
        else:
            return JsonResponse(form.errors)

        return redirect('core:index')

shop/templates/order/cart.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Корзина</h1>
    </div>
</div>

<div class="container">
    {% for item in cart %}
        {% with product=item.product %}
        <div class="row">
            <div class="col col-md-2">
                <a href="{{ product.get_absolute_url }}">
                    {% if product.image %}
                    <img class="img-responsive" src="{{ product.image.url }}" alt="{{ product.title }}" height="80">
                    {% else %}
                    <img class="img-responsive" src="{% static 'img/no_img.png' %}" alt="{{ product.title }}" height="80">
                    {% endif %}
                </a>
            </div>
            <div class="col">
                <h4>
                    <small>{{ product.title }}</small>
                </h4>
            </div>
            <div class="col-4 row">
                <div class="col text-md-right">
                    <h6>
                        {{ product.actual_price }} грн. <span class="text-muted">x</span>
                        {{ item.quantity }} <span class="text-muted"></span>
                        <strong>{{ item.total_price }} грн. <span class="text-muted"></span></strong>
                    </h6>
                </div>
                <form class="col text-md-right" action="{% url 'order:cart-remove' product.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-xs">x</button>
                </form>
            </div>
        </div>
        <hr>
        {% endwith %}
    {% empty %}
        <span class="h4">Корзина пуста</span>
    {% endfor %}
    {% if cart %}
    <div class="form-group btn-block btn-group">
        <a href="{% url 'order:cart-clear' %}" class="btn btn-block btn-danger mt-3">Очистить корзину</a>
        <a href="{% url 'order:checkout' %}" class="btn btn-block btn-success mt-3">Оформить заказ</a>
    </div>
    {% endif %}
</div>

{% endblock main %}

shop/templates/order/checkout.html
{% extends 'base.html' %}
{% load static custom_filters %}

{% block main %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Оформление заказа</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            {% if user.is_authenticated %}
            Привет, {{ user }}!
            <form class="form-group" action="" method="POST">
                {% csrf_token %}
                <input type="text" name="address" class="form-control" placeholder="Адрес доставки" required>
                <input type="text" name="comment" class="form-control" placeholder="Комментарий к заказу">
                <button class="btn btn-secondary btn-block" type="submit">Заказать</button>
            </form>
            {% else %}
            Введите необходимую информацию или <a href="" data-toggle="modal" data-target="#login">Войдите</a>
            <form class="form-group" action="" method="POST">
                {% csrf_token %}
                <input type="text" name="name" class="form-control" placeholder="Имя" required>
                <input type="text" name="surname" class="form-control" placeholder="Фамилия" required>
                <input type="text" name="phone" class="form-control" placeholder="Телефон" required>
                <input type="email" name="email" class="form-control" placeholder="Email" required>
                <input type="text" name="address" class="form-control" placeholder="Адрес доставки" required>
                <input type="text" name="comment" class="form-control" placeholder="Комментарий к заказу">
                <button class="btn btn-secondary btn-block" type="submit">Заказать</button>
            </form>
            {% endif %}
        </div>
        <div class="col">
            Корзина:<br>
            {% for item in cart %}
            <div class="row">
                {% with product=item.product %}
                <div class="col">{{ product.title }} x {{ item.quantity }}</div>
                <div class="col">{{ item.total_price }} грн.</div>
                <hr>
                {% endwith %}
            </div>
            {% empty %}
            <span class="h4">Корзина пуста</span>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock main %}