apps/users/urls.py
from django.contrib.auth.views import PasswordResetView
from django.urls import path
from django.views.generic import TemplateView

from apps.users.views import LoginView, LogoutView, ProfileView, RegisterView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('reset/', PasswordResetView.as_view(
        template_name='users/reset.html',
        success_url='/users/reset/done/'
    ), name='pw_reset'),
    path('reset/done/', TemplateView.as_view(
        template_name='users/reset_done.html'
    ), name='pw_reset_done'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('', include('apps.order.urls', namespace='order')),
    path('api/v1/', include('apps.api.v1.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('users/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('soon/', TemplateView.as_view(
        template_name='soon.html',
        extra_context={'title': 'some title'}
    ), name='soon'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apps/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.conf import settings
from django.core.mail import send_mail

from apps.users.managers import CustomUserManager
from apps.users.tasks import send_mail_task


class CustomUser(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, unique=True)
    bonus = models.PositiveIntegerField(default=0)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'custom user'
        verbose_name_plural = 'custom users'

    def email_user(self, subject, message, **kwargs):
        send_mail_task.delay(subject, message, [self.email], **kwargs)
        # send_mail(
        #     subject, message, settings.EMAIL_HOST_USER, [self.email], **kwargs
        # )

apps/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'email', 'phone', 'name', 'surname', 'password1', 'password2'
        )

apps/users/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, RedirectView, TemplateView
from django.http import JsonResponse

from apps.users.forms import RegisterForm


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:profile')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)

    def form_invalid(self, form):
        return JsonResponse(form.errors, status=400)


class LogoutView(RedirectView):
    pattern_name = 'core:index'

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'


class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        user = form.save()
        user.email_user('successfully registration', 'WELCOME')
        login(self.request, user)
        return super().form_valid(form)

shop/templates/users/modals/login.html
<div class="modal" id="login">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="container">

                <form class="form-group" action="{% url 'users:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="text-center my-4">
                        <p class="h3">Авторизация</p>
                    </div>
                    <input id="username" type="text" name="username" class="form-control my-2" placeholder="Введите email или номер телефона" required
                        autofocus>
                    <small id="login-error" class="text-danger"></small>
                    <input id="password" type="password" name="password" class="form-control mt-2" placeholder="Пароль"
                        required>
                    <div class="text-center">
                        <a href="{% url 'users:pw_reset' %}" class="text-secondary">забыли пароль?</a>
                    </div>
                    <button id="loginBtn" class="btn btn-primary btn-block" type="submit">Войти</button>
                    <button type="button" class="btn btn-block btn-outline-secondary" data-dismiss="modal"
                        data-toggle="modal" data-target="#register">Зарегистрироваться</button>
                </form>

            </div>
        </div>
    </div>
</div>

shop/templates/users/modals/register.html
<div class="modal" id="register">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="container">
                <form id="register-form" class="form-group" action="{% url 'users:register' %}" method="POST">
                    {% csrf_token %}
                    <div class="text-center my-4">
                        <p class="h3">Регистрация</p>
                    </div>
                    <input id="reg-email" type="email" name="email" class="form-control my-2" placeholder="Email" required>
                    <small id="reg-email-error" class="text-danger"></small>
                    <input id="reg-phone" type="phone" name="phone" class="form-control my-2" placeholder="Телефон" required>
                    <small id="reg-phone-error" class="text-danger"></small>
                    <input id="reg-name" type="text" name="name" class="form-control my-2" placeholder="Имя" required>
                    <input id="reg-surname" type="text" name="surname" class="form-control my-2" placeholder="Фамилия" required>
                    <input id="reg-password1" type="password" name="password1" class="form-control my-2" placeholder="Пароль" required>
                    <input id="reg-password2" type="password" name="password2" class="form-control my-2" placeholder="Повторите пароль" required>
                    <small id="reg-password2-error" class="text-danger"></small>
                    <button id="register-btn" class="btn btn-primary btn-block" type="submit">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>