apps/core/urls.py
from django.urls import path

from apps.core.views import (
    category_detail, product_list, product_detail,
    contact_us,
    IndexView, IndexTemplateView, CategoryListView, CategoryDetailView,
    ContactUsFormView, ProductListView
)

app_name = 'core'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<slug>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<slug_category>/<pk>/', product_detail, name='product-detail'),
    path('contact_us/', ContactUsFormView.as_view(), name='contact-us'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('', include('apps.order.urls', namespace='order')),
    path('api/v1/', include('apps.api.v1.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('users/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('soon/', TemplateView.as_view(
        template_name='soon.html',
        extra_context={'title': 'some title'}
    ), name='soon'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/templates/modals/contact_us.html
<div class="modal" id="contact-us">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form" action="{% url 'core:contact-us' %}" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">Форма обратной связи</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    <input name="email" type="email" class="form-control" placeholder="Email" autofocus required>
                    <input name="phone" type="text" class="form-control" placeholder="Телефон" required>
                    <input name="name" type="text" class="form-control" placeholder="Имя" required>
                    <input name="subject" type="text" class="form-control" placeholder="Тема" required>
                    <input name="message" type="text" class="form-control" placeholder="Сообщение">
                </div>

                <div class="modal-footer btn-block">
                    <button type="submit" class="btn btn-outline-success btn-block">Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>