apps/core/urls.py
from django.urls import path

from apps.core.views import (
    category_detail, product_list, product_detail,
    contact_us,
    IndexView, IndexTemplateView, CategoryListView, CategoryDetailView,
    ContactUsFormView, ProductListView
)

app_name = 'core'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<slug>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<slug_category>/<pk>/', product_detail, name='product-detail'),
    path('contact_us/', ContactUsFormView.as_view(), name='contact-us'),
]

apps/order/urls.py
from django.urls import path

from apps.order.views import (
    CartTemplateView, CartAddView, CartRemoveView, CartClearView,
    CheckoutTemplateView,
)

app_name = 'order'

urlpatterns = [
    path('cart/', CartTemplateView.as_view(), name='cart'),
    path('add/<pk>/', CartAddView.as_view(), name='cart-add'),
    path('remove/<pk>/', CartRemoveView.as_view(), name='cart-remove'),
    path('clear/', CartClearView.as_view(), name='cart-clear'),
    path('checkout/', CheckoutTemplateView.as_view(), name='checkout'),
]

apps/users/urls.py
from django.contrib.auth.views import PasswordResetView
from django.urls import path
from django.views.generic import TemplateView

from apps.users.views import LoginView, LogoutView, ProfileView, RegisterView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('reset/', PasswordResetView.as_view(
        template_name='users/reset.html',
        success_url='/users/reset/done/'
    ), name='pw_reset'),
    path('reset/done/', TemplateView.as_view(
        template_name='users/reset_done.html'
    ), name='pw_reset_done'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
    path('', include('apps.order.urls', namespace='order')),
    path('api/v1/', include('apps.api.v1.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('users/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('soon/', TemplateView.as_view(
        template_name='soon.html',
        extra_context={'title': 'some title'}
    ), name='soon'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apps/core/models.py
from autoslug import AutoSlugField

from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver

from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

from django.utils.translation import gettext_lazy as _

from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    """
        Класс описывает таблицу и поля в базе данных для сущности Category
    """
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    # slug = models.SlugField(allow_unicode=True, default='', blank=True)
    slug = AutoSlugField(
        populate_from='title',
        always_update=True,
        unique=True,
        null=True
    )

    class Meta:
        verbose_name = _('category')  # отображение названия модели в админке
        verbose_name_plural = _('categories')  # во множественном числе
        ordering = ('title',)  # сортировка по title (в алфавитном порядке)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:category-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)



class Tag(models.Model):
    name = models.CharField(max_length=128)

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'

    def __str__(self):
        return self.name


class Product(models.Model):
    """
        Класс описывает таблицу и поля в базе данных для сущности Product
    """
    title = models.CharField(
        verbose_name='название',
        max_length=255,
        help_text='Максимальная длина 255 символов',
    )
    category = models.ForeignKey(
        Category,
        verbose_name='категория',
        on_delete=models.SET_NULL,
        null=True,
        related_name='products',
    )
    tag = models.ManyToManyField(
        Tag,
        verbose_name='теги',
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    image = models.ImageField(
        verbose_name='изображение',
        upload_to='product',
        blank=True,
        null=True,
    )
    price = models.FloatField(
        verbose_name='цена',
    )
    discount = models.FloatField(
        verbose_name='скидка',
        validators=[
            MinValueValidator(0.0),
            MaxValueValidator(100.0)
        ],
        default=0,
    )
    bonus = models.PositiveIntegerField(
        verbose_name='бонус',
        default=1,
    )
    in_stock = models.BooleanField(
        verbose_name='в наличии?',
        default=True,
    )

    created_at = models.DateTimeField(
        verbose_name='дата создания',
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name='дата последнего изменения',
        auto_now=True,
    )

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('-pk',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:product-detail', kwargs={
            'slug_category': self.category.slug,
            'pk': self.pk
        })

    @property
    def actual_price(self):
        return round(self.price * (1 - self.discount / 100), 2)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Contacts(models.Model):
    title = models.CharField(max_length=128)
    address = models.TextField()
    phone = models.CharField(max_length=20)

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(
            pk=1,
            defaults={
                'title': 'Shop',
                'address': 'Kharkiv, some street',
                'phone': '0661234567'
            }
        )
        return obj


class ContactUs(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=12, blank=True, null=True)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'contact us'

shop/templates/components/footer.html
<div class="container">
    <button class="btn btn-lg btn-block btn-outline-warning" data-toggle="modal" data-target="#contact-us">Обратная связь</button>
    <p class="m-0 py-3 text-center text-white">&copy; KlooM 2020</p>
</div>

shop/templates/components/header.html
{% load custom_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}">Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}" class="btn btn-primary my-2 my-sm-0 ml-auto">Личный кабинет, {{ user }}</a>
                <a href="{% url 'users:logout' %}" class="btn btn-danger my-2 my-sm-0 ml-sm-2">Выйти</a>
            {% else %}
                <button type="button" class="btn btn-success my-2 my-sm-0 ml-auto login-modal" data-toggle="modal" data-target="#login">Войти</button>
                <button type="button" class="btn btn-primary my-2 my-sm-0 ml-sm-2 register-modal" data-toggle="modal" data-target="#register">Зарегистрироваться</button>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container">
    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="{% url 'core:index' %}">Главная</a>
            <a class="p-2 text-muted" href="{% url 'core:product-list' %}">Все товары</a>
            <a class="p-2 text-muted dropdown-toggle" href="#" id="dropdownCategories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Категории</a>
            <div class="dropdown-menu" aria-labelledby="dropdownCategories">
                {% for category in category_list %}
                    <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.title|title }} ({{ category.products.count }})</a>
                {% endfor %}
            </div>
            <a class="p-2 text-muted" href="#">О нас</a>
            <a class="p-2 text-muted" href="#">Контакты</a>
            <a class="p-2 text-muted" href="{% url 'order:cart' %}">🛒Корзина</a>
        </nav>
    </div>
</div>